name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-interpreter:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc make
      - name: Create build dir
        run: mkdir build
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!' 
          make all
      - name: Test with benchmark
        shell: powershell
        working-directory: ./benchmark
        run: |
          python benchmark.py >> "$GITHUB_OUTPUT"
